### ISSUE TITLE
Drop deprecated functions in 2.0.0 ?

### ISSUE THREAD

**Issue by katajakasa** [kode54/dumb#54]
There is a pile of deprecated functions, and have been since 0.9.3, Would it be time to drop them in 2.0.0 ?

**Comment by SimonN** [comment]
I rely on the deprecated `duh_render` because I couldn't guess how to use `duh_render_int` and `duh_render_float`: What buffer do they expect, who should create that, who should manage its lifetime, etc.

I'm up for redesigning my DUMB-using code, but I'd need documentation for the alternatives. Or maybe keep this one function?

I have no problem dropping other deprecated functions.

I'd also be fine with dropping the `DUMB_YEAR`, `DUMB_MONTH`, `DUMB_DAY` macros, because they've been deprecated since 2002. We should check the `DUMB_MAJOR_VERSION` instead, which I already do.

**Comment by katajakasa** [comment]
duh_render was deprecated so recently, that it wouldn't imo make sense to drop it.

All the stuff from 0.9.3 and earlier could probably go, though. I mean, people HAVE had a few years time to fix their code :)

**Comment by SimonN** [comment]
This issue can be closed because #55 got merged.
