### ISSUE TITLE
Won't Compile with MinGW32

### ISSUE THREAD

**Issue by NewCreature** [kode54/dumb#67]
There's another issue with `dumb_off_t`. On my 32-Bit Windows machine with MinGW, off_t is 32-bit so DUMB fails to compile.

**Comment by Rondom** [comment]
I tested this with both 32 and 64-bit MingW-W64. What MingW-version are we talking about here?
off_t is 32-bit as long as you do not compile with `-D_FILE_OFFSET_BITS=64`

**Comment by NewCreature** [comment]
It says `gcc version 5.3.0 (GCC)`.

**Comment by Rondom** [comment]
Hmm, that 5.3 sounds old. Is it the "old" MingW, i.e. not MingW-W64? Can you provide a link to the toolchain you are using?

**Comment by Rondom** [comment]
The first version with support for _FILE_OFFSET_BITS was  MinGW-W64 v2.0.rc1 released on Aug 7, *2011*. Since that is quite some time ago, I assume that you are using the mingw.org-MinGW.

Please confirm and ideally send me a link to the toolchain you are using.

**Comment by NewCreature** [comment]
[http://www.mingw.org](url)
I used the installer.

**Comment by Rondom** [comment]
Oh, I am not an expert on this (not doing much Windows development), so please form your own opinion from other sources. My impression was that by now MinGW-W64 is more actively developed from the fact that Linux distributions like Fedora or Debian/Ubuntu have switched to shipping MingW-W64 and that I have seen people using MSYS2 mostly.

I will have a look into how to detect the original MinGW in the code, so that it works nicely with both.
